"use client";

import { useMemo, useState } from "react";
import { Check, Search, X } from "lucide-react";
import type { OrganizationMember } from "@/services/auth.service";

export function AddCommitteeMembersModal({ members, onClose, onAdd }: { members: OrganizationMember[]; onClose: () => void; onAdd: (memberIds: string[]) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const visible = useMemo(() => members.filter((member) => `${member.name} ${member.position} ${member.role}`.toLowerCase().includes(query.toLowerCase())), [members, query]);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  async function submit() { if (!selected.length) { setError("Select at least one member."); return; } setSaving(true); setError(""); try { await onAdd(selected); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to add members."); setSaving(false); } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div><p className="text-xs font-bold uppercase tracking-wide text-[#2868ed]">Committee</p><h2 className="mt-1 text-xl font-extrabold">Add members</h2></div><button onClick={onClose} disabled={saving} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" type="button"><X className="size-5" /></button></div><div className="p-5"><label className="flex h-10 items-center gap-2 rounded-xl border border-slate-200 px-3"><Search className="size-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search available members" /></label><div className="mt-3 max-h-72 divide-y overflow-y-auto rounded-xl border border-slate-200">{visible.map((member) => { const active = selected.includes(member.id); return <button key={member.id} type="button" onClick={() => toggle(member.id)} className="flex w-full items-center gap-3 px-3 py-2.5 text-left hover:bg-slate-50"><span className="flex size-8 items-center justify-center rounded-full bg-[#213f68] text-[10px] font-bold text-white">{member.name.split(/\s+/).map((part) => part[0]).slice(0, 2).join("")}</span><span className="flex-1"><span className="block text-sm font-semibold">{member.name}</span><span className="block text-xs text-slate-500">{member.position || member.role}</span></span><span className={`flex size-5 items-center justify-center rounded-md border ${active ? "border-[#2868ed] bg-[#2868ed] text-white" : "border-slate-300"}`}>{active ? <Check className="size-3.5" /> : null}</span></button>; })}{!visible.length ? <p className="p-6 text-center text-sm text-slate-500">No members available.</p> : null}</div>{error ? <p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p> : null}</div><div className="flex justify-end gap-3 border-t border-slate-200 p-5"><button onClick={onClose} disabled={saving} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600" type="button">Cancel</button><button onClick={submit} disabled={saving} className="rounded-xl bg-[#213f68] px-4 py-2 text-sm font-semibold text-white disabled:opacity-60" type="button">{saving ? "Adding..." : `Add ${selected.length || ""} member${selected.length === 1 ? "" : "s"}`}</button></div></div></div>;
}
