"use client";

import { X } from "lucide-react";

type MemberProfile = { initials: string; name: string; role: string; committee: string; skills: string[]; workload: number; reliability: string; availability: string };

export function MemberProfileModal({ member, onClose }: { member: MemberProfile; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="member-profile-title"><div className="w-full max-w-md rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div className="flex items-center gap-3"><span className="flex size-11 items-center justify-center rounded-full bg-[#213f68] text-sm font-bold text-white">{member.initials}</span><div><h2 id="member-profile-title" className="text-lg font-extrabold">{member.name}</h2><p className="text-sm text-slate-500">{member.role}</p></div></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X className="size-5" /></button></div><div className="space-y-4 p-5"><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Committee</p><p className="mt-1 text-sm font-semibold text-violet-700">{member.committee}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">Skills</p><div className="mt-2 flex flex-wrap gap-1.5">{member.skills.length ? member.skills.map((skill) => <span key={skill} className="rounded bg-[#e8eef7] px-2 py-1 text-xs text-[#214574]">{skill}</span>) : <span className="text-sm text-slate-400">No skills listed.</span>}</div></div><div className="grid grid-cols-3 gap-3 rounded-xl bg-slate-50 p-3 text-center"><div><p className="text-sm font-bold text-slate-800">{member.workload}%</p><p className="text-[10px] text-slate-500">Workload</p></div><div><p className="text-sm font-bold text-slate-800">{member.reliability}</p><p className="text-[10px] text-slate-500">Reliability</p></div><div><p className="text-sm font-bold text-emerald-600">{member.availability}</p><p className="text-[10px] text-slate-500">Availability</p></div></div></div></div></div>;
}
